version: "3.8"
services:
  timon-sql-server-db:
    container_name: TIMON-MS-SQLSERVER
    restart: always
    hostname: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SQL_DB_PASS}
      ACCEPT_EULA: ${SQL_ELUA}